--as intrusções listadas aqui serão executadas quando a aplicação subir
CREATE TABLE CLIENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC (20,2)
);

CREATE TABLE PEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES CLIENTE (ID), --FOREING_KEY
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20,2) -- 20 POSIÇÕES E DOIS DECIMAIS
);

CREATE TABLE ITEM_PEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDO (ID), --FOREING_KEY
    PRODUTO_ID INTEGER REFERENCES PRODUTO (ID), --FOREING_KEY
    QUANTIDADE INTEGER
);